app_proj/urls.py
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
PROJECT/URLS.py
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

from django.conf.urls import include, url
from django.contrib import admin
import allauth.account.views as AV

import common.views as BV 
import kingdoms.views as KV 
import members.views as MV 
import campaign.views as GV 
import central.views as CV 


kingdoms_url = [
    url(r'^kingdoms/$', KV.kingdoms, name='kingdoms'),
    url(r'^special_cards/$', KV.special_cards, name='special_cards'),
    url(r'^game_rules/$', KV.game_rules, name='game_rules'),
    url(r'^reference_jx/([a-zA-Z0-9_]+)/$', KV.reference_jx, name='reference_jx'),
    
    url(r'^data_load/$', KV.data_load, name='data_load'),
    url(r'^manager_jx/([a-zA-Z0-9_]+)/$', KV.manager_jx, name='manager_jx'),
]


members_url = [    
    url(r"^accounts/signup/$", AV.signup, name="account_signup"),        # must preserve allauth name field for its internal calls
    url(r"^accounts/login/$", AV.login, name="account_login"),
    url(r"^accounts/logout/$", AV.logout, name="account_logout"),

    url(r"^accounts/email/$", MV.email, name="account_email"),
    url(r"^accounts/confirm-email/(?P<key>[-:\w]+)/$", AV.confirm_email, name="account_confirm_email"),
    url(r"^accounts/confirm-email/$", AV.email_verification_sent, name="account_email_verification_sent"),    # used when email still requires confirmation
 
    url(r"^accounts/password/change/$", AV.password_change, name="account_change_password"),
   	url(r"^accounts/password/reset/$", MV.password_reset, name="account_reset_password"),
    url(r"^accounts/password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$", MV.password_reset_from_key, name="account_reset_password_from_key"),
    url(r"^accounts/inactive/$", AV.account_inactive, name="account_inactive"),         

    url(r'^auth_dialog/', MV.dialog),
    url(r'^messages/', MV.messages, name='messages'),
    url(r'^messages_jx/([a-zA-Z0-9_]+)/$', MV.messages_jx, name='messages_jx'),
    url(r'^profile/', MV.profile, name='profile'),
    url(r'^profile_jx/([a-zA-Z0-9_]+)/$', MV.profile_jx, name='profile_jx'),

    url(r'^members_admin/', MV.members_admin, name='members_admin'),
    url(r'^members_jx/([a-zA-Z0-9_]+)/$', MV.members_jx, name='members_jx')    
]


campaign_url = [
    url(r'^campaign/$', GV.campaign, name='campaign'),
    url(r'^campaign_jx/([a-zA-Z0-9_]+)/$', GV.campaign_jx, name='campaign_jx'),
]


central_url = [
    url(r'^headquarters/$', CV.headquarters, name='headquarters'),
    # url(r'^view_profile/([a-zA-Z0-9_]+)', CV.view_profile, name='view_profile'),
    # url(r'^store/$', CV.store, name='store'),
    # url(r'^central_jx/([a-zA-Z0-9_]+)/$', CV.central_jx, name='central_jx'),
    # 
    url(r'^master/', CV.master, name='master'),
    #url(r'^master_jx/([a-zA-Z0-9_]+)/$', CV.master_jx, name='master_jx'),
]


urlpatterns = [
    url(r'^$', CV.landing_page, name='landing_page'),

    url(r'^members/', include(members_url)),   # do not use a namespace, breaks allauth reverse urls 
    url(r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),	# necessary for postman
    
    url(r'^reference/', include(kingdoms_url, namespace='kingdoms')),
    url(r'^campaign/', include(campaign_url, namespace='campaign')),
    url(r'^central/', include(central_url, namespace='central')),
    
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', BV.not_found, name='not_found'),
]

central/views.py
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
CENTRAL/VIEWS.py
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

import json

from django.shortcuts import render
from django.http import JsonResponse
from django.utils.safestring import mark_safe
from django.contrib.auth.decorators import user_passes_test
from django.views.decorators.csrf import ensure_csrf_cookie

import common.utility as CU
import kingdoms.kingdoms as KK
import members.models.members as MM


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
CENTRAL PAGES
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""


def landing_page(request):
    context = {
        'topRanks': mark_safe(json.dumps({})),
    }
    return render(request, 'landing_page.html', context)


def headquarters(request):
    userDecks = MM.Decks_Reporter.GetDecksFT(request.user)
    kingdoms = KK.Reporter.GetKingdoms()
    arenaReport = None
    tourneyReport = None
    context = {
        'userDecks': mark_safe(json.dumps(userDecks)),
        'kingdoms': mark_safe(json.dumps(kingdoms)),
    }
    return render(request, 'headquarters.html', context)


@ensure_csrf_cookie
def master(request):
    kingdomCards = KK.Importer.GetKingdomCards()
    context = {
        'kingdomCards': mark_safe(json.dumps(kingdomCards)),
    }
    return render(request, 'data_master.html', context)

central/templates/data_master.html
{% extends "base_nav.html" %}
{% load utility_ttags %}
{% load staticfiles %}

{% comment %}
{% endcomment %}

{% block content %}


<div id="title_section" class="row">
    <div class="col-xs-12 format_center">
        <div class="inner_margin1 frame_header">
            <span class="font_title">Data Master</span>
        </div>
    </div>
</div>


<div id="loadTables_section" class="row">
    
    <div class="col-xs-12">
        <div class="display_table">
            <div class="display_row">
                <div class="display_cellM">
                    <div class="inner_margin1 frame_header" style="margin-right: 0px;">
                        <span class="font_section">Kingdoms</span>
                    </div>
                </div>
                <div class="display_cellT" style="width: 100%;">
                    <div class="display_block frame_header format_separator">
                    </div>
                </div>
            </div>
        </div>
        <div style="display: none;">{% ctrl_status "kingdoms" %}</div>
    </div>
    
    <div class="col-xs-12 col-sm-6 col-xxl-4">
        <div class="display_block inner_margin1 outer_padding2 frame_entry">
            {% ctrl_label "load" "Load Tables" "font_strong" %}
            <div class="display_table">
                <div class="display_row">
                    <div class="display_cellT format_center" style="min-width: 200px;">
                        <br>
                        {% ctrl_button "kingdoms" "Load Kingdoms" %}
                        <br><br>
                        {% ctrl_button "cards" "Load Cards" %}
                        <br><br>
                        {% ctrl_button "reset" "Clear Tables" %} 
                    </div>
                    <div class="display_cellT">
                        {% ctrl_table "kingdomCards" %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="col-xs-12 col-sm-6 col-xxl-4">
        <div class="display_block inner_margin1 outer_padding2 frame_entry">
            {% ctrl_label "load" "Delete" "font_strong" %}
            <div class="display_table format_full">
                <div class="display_row">
                    <div class="display_cellT format_center" style="width: 100%;">
                        <br>
                        {% ctrl_button "deleteG" "Delete Your Game" %}
                        <br> <br>
                        {% ctrl_button "deleteDeck" "Delete Your Deck" %}
                        <br> <br>
                    </div>
                    <div class="display_cellT">
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="col-xs-12 col-sm-6 col-xxl-4">
        <div class="display_block inner_margin1 outer_padding2 frame_entry">
            {% ctrl_label "load" "Initialize DB" "font_strong" %}
            <div class="display_table format_full">
                <div class="display_row">
                    <div class="display_cellT format_center" style="width: 100%;">
                        <br>
                        {% ctrl_button "campaignUser" "Create Campaign User" %}
                        <br> <br>
                    </div>
                    <div class="display_cellT">
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


<!-- SCRIPTS -->

<script>

$(document).ready(function()
{      
    $('body').css('cursor', 'wait');
    
    
    var jTable = $.parseJSON('{{ kingdomCards | escapejs }}');      //cl(jTable);
    DisplayKingdoms(jTable);
    
    $('#kingdoms_button').click(function() {
        ImportKingdoms();
    });
    
    $('#cards_button').click(function() {
        ImportCards();
    });
    
    $('#reset_button').click(function() {
        ClearTables();
    });
    
    $('#deleteG_button').click(function() {
        DeleteGame();
    });
    
    $('#deleteDeck_button').click(function() {
        DeleteDecks();
    });
    
    $('#campaignUser_button').click(function() {
        CreateCampaignUser();
    });

    $('body').css('cursor', 'default');
});


function DisplayKingdoms(p_kingdoms)
{
    if (p_kingdoms.data.length != 0)
    {
        var fullT = JSONtoFullTable(p_kingdoms.data);
        SetDataTable('#kingdomCards_table', fullT, p_kingdoms.colFmt);
    }
    else
    {
        $('#kingdomCards_table').html("<div style='margin: 4px;'>No kingdoms available.</div>");
    }
}


function DisableForm()
{
    $('#kingdoms_status').parent().parent().hide(); 
    $('#kingdoms_button').prop('disabled', true);
    $('#cards_button').prop('disabled', true);
    $('#reset_button').prop('disabled', true);
    $('body').css('cursor', 'wait');
}


function EnableForm()
{
    $('#kingdoms_button').prop('disabled', false);
    $('#cards_button').prop('disabled', false);
    $('#reset_button').prop('disabled', false);
    $('body').css('cursor', 'default');    
}


function ImportKingdoms()
{
    DisableForm();
    
    $.ajax({
        type: 'POST',
        url: '{% url "kingdoms:manager_jx" "import_kingdoms" %}',
        success: function(p_data) {     //cl(p_data);
            DisplayKingdoms(p_data);
        }, 
        error: function(p_err) {
            ErrorToStatus(p_err.responseText, "ImportKingdoms()", '#kingdoms_status');
        },
        complete: function() {
            EnableForm();
        }
    });
}


function ImportCards()
{
    DisableForm();
    
    $.ajax({
        type: 'POST',
        url: '{% url "kingdoms:manager_jx" "import_cards" %}',
        success: function(p_data) {     //cl(p_data);
            DisplayKingdoms(p_data);
        }, 
        error: function(p_err) {
            ErrorToStatus(p_err.responseText, "ImportRaces()", '#kingdoms_status');
        },
        complete: function() {
            EnableForm();
        }
    });
}


function ClearTables()
{
    DisableForm();
    
    $.ajax({
        type: 'POST',
        url: '{% url "kingdoms:manager_jx" "clear_tables" %}',
        success: function(p_data) {     //cl(p_data);
            DisplayKingdoms(p_data);
        }, 
        error: function(p_err) {
            ErrorToStatus(p_err.responseText, "ClearTables()", '#kingdoms_status');
        },
        complete: function() {
            EnableForm();
        }
    });
}


function DeleteGame()
{
    DisableForm();
    
    $.ajax({
        type: 'POST',
        url: '{% url "campaign:campaign_jx" "delete_game" %}',
        success: function(p_data) {     cl(p_data);
            var nothing = true;
        }, 
        error: function(p_err) {
            ErrorToStatus(p_err.responseText, "ClearTables()", '#kingdoms_status');
        },
        complete: function() {
            EnableForm();
        }
    });
}


function DeleteDecks()
{
    DisableForm();
    
    $.ajax({
        type: 'POST',
        url: '{% url "campaign:campaign_jx" "delete_decks" %}',
        success: function(p_data) {     cl(p_data);
            var nothing = true;
        }, 
        error: function(p_err) {
            ErrorToStatus(p_err.responseText, "DeleteDecks()", '#kingdoms_status');
        },
        complete: function() {
            EnableForm();
        }
    });
}



function CreateCampaignUser()
{
    DisableForm();
    
    $.ajax({
        type: 'POST',
        url: '{% url "campaign:campaign_jx" "create_user" %}',
        success: function(p_data) {     cl(p_data);
            var nothing = true;
        }, 
        error: function(p_err) {
            ErrorToStatus(p_err.responseText, "CreateCampaignUser()", '#kingdoms_status');
        },
        complete: function() {
            EnableForm();
        }
    });
}


</script>

{% endblock content %}

central/templates/headquarters.html
{% extends "base_nav.html" %}
{% load utility_ttags %}
{% load staticfiles %}


{% block content %}


<div id="title_section" class="row">
    <div class="col-xs-12 format_center">
        <div class="inner_margin1 frame_header">
            <span class="font_title">Headquarters</span>
        </div>
    </div>
</div>


<div id="decks_section" class="row">
    
    <div class="col-xs-12">
        <div class="display_table">
            <div class="display_row">
                <div class="display_cellM">
                    <div class="inner_margin1 frame_header" style="margin-right: 0px;">
                        <span class="font_section">My Decks</span>
                    </div>
                </div>
                <div class="display_cellT" style="width: 100%;">
                    <div class="display_block frame_header format_separator">
                    </div>
                </div>
            </div>
        </div>
        <div style="display: none;">{% ctrl_status "decks" %}</div>
    </div>
    
    <div class="col-xs-12 col-sm-6 col-lg-4">
        <div class="display_block inner_margin1 outer_padding2 frame_entry">

            <div id="table_group">
                {% ctrl_label "chs" "Your Decks" "font_strong" %}
                {% ctrl_table "decks" %}
            </div>

            <div id="choose_group">
                {% ctrl_label "chs" "Choose Your Deck" "font_strong" %}
                {% ctrl_select "kingdom" "Kingdom" %}
                <div class="format_center">
                    {% ctrl_button "saveDeck" "Save Deck" %} 
                    {% ctrl_label "userMsg" %}
                </div>
            </div>

            <br>
            <div class="display_block">
                {% ctrl_listing "deckCnt" "Decks Unlocked" %} 
            </div>
            {% ctrl_listing "kingdomCnt" "Total Kingdoms" %}

        </div>
    </div>

    <div class="col-xs-12 col-sm-6 col-lg-4">
        <div class="display_block inner_margin1 outer_padding2 frame_entry">

            {% ctrl_label "chs" "Campaign Progress" "font_strong" %}

            <div class="display_block">
                {% ctrl_listing "camp1" "Normal" %} 
            </div>
            <div class="display_block">
                {% ctrl_listing "camp2" "Hard" %} 
            </div>
            <div class="display_block">
                {% ctrl_listing "camp3" "Nightmare" %} 
            </div>
 
        </div>
    </div>
    
</div>


<div id="arena_section" class="row">
    
    <div class="col-xs-12">
        <div class="display_table">
            <div class="display_row">
                <div class="display_cellM">
                    <div class="inner_margin1 frame_header" style="margin-right: 0px;">
                        <span class="font_section">Arena</span>
                    </div>
                </div>
                <div class="display_cellT" style="width: 100%;">
                    <div class="display_block frame_header format_separator">
                    </div>
                </div>
            </div>
        </div>
        <div style="display: none;">{% ctrl_status "decks" %}</div>
    </div>
    
    <div class="col-xs-12 col-sm-6 col-lg-4">
        <div class="display_block inner_margin1 outer_padding2 frame_entry">

            {% ctrl_label "chs" "My Record" "font_strong" %}

        </div>
    </div>
    
</div>


<div id="tourney_section" class="row">
    
    <div class="col-xs-12">
        <div class="display_table">
            <div class="display_row">
                <div class="display_cellM">
                    <div class="inner_margin1 frame_header" style="margin-right: 0px;">
                        <span class="font_section">Tournaments</span>
                    </div>
                </div>
                <div class="display_cellT" style="width: 100%;">
                    <div class="display_block frame_header format_separator">
                    </div>
                </div>
            </div>
        </div>
        <div style="display: none;">{% ctrl_status "decks" %}</div>
    </div>
    
    <div class="col-xs-12 col-sm-6 col-lg-4">
        <div class="display_block inner_margin1 outer_padding2 frame_entry">

            {% ctrl_label "chs" "My Record" "font_strong" %}

        </div>
    </div>
    
</div>


<script>


$(document).ready(function()
{      
    $('body').css('cursor', 'wait');
    
    var authUser = ( '{{ user.is_authenticated }}' == "True" ? true : false );      
    
    var kingdoms = $.parseJSON('{{ kingdoms | escapejs }}');        
    var userDecks = $.parseJSON('{{ userDecks | escapejs }}');      

    if (authUser && userDecks && userDecks.data.length > 0)
    {
        $('#table_group').show();
        $('#choose_group').hide();

        var fullT = JSONtoFullTable(userDecks.data);
        SetDataTable('#decks_table', fullT, userDecks.colFmt);
    }
    else if (authUser)
    {
        $('#table_group').hide();
        $('#choose_group').show();

        $.each(kingdoms, function(key, value) {
            $("#kingdom_select").append($('<option>', {value : key }).text(value));
        });
        
        $('#saveDeck_button').click(function() {
            SaveDeck();
        });
    }
    else 
    {
        $('#table_group').hide();
        $('#choose_group').show();

        $.each(kingdoms, function(key, value) {
            $("#kingdom_select").append($('<option>', {value : key }).text(value));
        });
        
        $('#saveDeck_button').hide();
        $('#userMsg_label').show();
        $('#userMsg_label').text("* Decks are for registered users. *");
    }

    $('#deckCnt_listing').text(userDecks.data.length );
    $('#kingdomCnt_listing').text(kingdoms.length);


    //
    $('body').css('cursor', 'default');
});


function DisableForm()
{
    $('#_select').prop('disabled', true);
    $('body').css('cursor', 'wait');
}

function EnableForm()
{
    $('#_select').prop('disabled', false);
    $('body').css('cursor', 'default');    
}

function SaveDeck()
{    
    var kingdom = $('#kingdom_select option:selected').text();

    DisableForm();
    
    $.ajax({
        type: 'POST',
        url: '{% url "members_jx" "save_deck" %}',
        data: {'kingdom': kingdom,},
        success: function(p_data) {     cl(p_data);
            
            window.location.reload(false);
            
        }, 
        error: function(p_err) {
            ErrorToStatus(p_err.responseText, "SaveDeck()", '#error_status');
        },
        complete: function() {
            EnableForm();
        }
    });
}


</script>

{% endblock content %}

central/templates/landing_page.html
{% extends "base_nav.html" %}
{% load utility_ttags %}
{% load staticfiles %}

{% comment %}
{% endcomment %}

{% block content %}


<style>

.font_titleLnd {
    padding: 20px 0px 0px 0px;
    color: DarkGoldenRod ;
    font-size: 250%;
    font-weight: bolder;    
}

</style>

<div id="" class="row">
    
    <div class="col-xs-12">
        <div class="format_center" style="padding-top: 100px;">
            <img src="{% static 'graphics/era_title.png' %}" style=""/> <br>
            <span class="font_titleLnd">Online</span> <br>
            <img src="{% static 'graphics/era_logo.png' %}" style="padding-top: 100px;"/> <br>
        </div>
    </div>
    
</div>


<!-- SCRIPTS -->

<script>


$(document).ready(function()
{      
    $('body').css('cursor', 'wait');
    

    $('body').css('cursor', 'default');
});


</script>

{% endblock content %}