app_proj/urls.py
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
PROJECT/URLS.py
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

from django.conf.urls import include, url
from django.contrib import admin
import allauth.account.views as AV

import common.views as BV 
import kingdoms.views as KV 
import members.views as MV 
import campaign.views as GV 
import central.views as CV 


kingdoms_url = [
    url(r'^kingdoms/$', KV.kingdoms, name='kingdoms'),
    url(r'^special_cards/$', KV.special_cards, name='special_cards'),
    url(r'^game_rules/$', KV.game_rules, name='game_rules'),
    url(r'^reference_jx/([a-zA-Z0-9_]+)/$', KV.reference_jx, name='reference_jx'),
    
    url(r'^data_load/$', KV.data_load, name='data_load'),
    url(r'^manager_jx/([a-zA-Z0-9_]+)/$', KV.manager_jx, name='manager_jx'),
]


members_url = [    
    url(r"^accounts/signup/$", AV.signup, name="account_signup"),        # must preserve allauth name field for its internal calls
    url(r"^accounts/login/$", AV.login, name="account_login"),
    url(r"^accounts/logout/$", AV.logout, name="account_logout"),

    url(r"^accounts/email/$", MV.email, name="account_email"),
    url(r"^accounts/confirm-email/(?P<key>[-:\w]+)/$", AV.confirm_email, name="account_confirm_email"),
    url(r"^accounts/confirm-email/$", AV.email_verification_sent, name="account_email_verification_sent"),    # used when email still requires confirmation
 
    url(r"^accounts/password/change/$", AV.password_change, name="account_change_password"),
   	url(r"^accounts/password/reset/$", MV.password_reset, name="account_reset_password"),
    url(r"^accounts/password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$", MV.password_reset_from_key, name="account_reset_password_from_key"),
    url(r"^accounts/inactive/$", AV.account_inactive, name="account_inactive"),         

    url(r'^auth_dialog/', MV.dialog),
    url(r'^messages/', MV.messages, name='messages'),
    url(r'^messages_jx/([a-zA-Z0-9_]+)/$', MV.messages_jx, name='messages_jx'),
    url(r'^profile/', MV.profile, name='profile'),
    url(r'^profile_jx/([a-zA-Z0-9_]+)/$', MV.profile_jx, name='profile_jx'),

    url(r'^members_admin/', MV.members_admin, name='members_admin'),
    url(r'^members_jx/([a-zA-Z0-9_]+)/$', MV.members_jx, name='members_jx')    
]


campaign_url = [
    url(r'^campaign/$', GV.campaign, name='campaign'),
    url(r'^campaign_jx/([a-zA-Z0-9_]+)/$', GV.campaign_jx, name='campaign_jx'),
]


central_url = [
    url(r'^headquarters/$', CV.headquarters, name='headquarters'),
    # url(r'^view_profile/([a-zA-Z0-9_]+)', CV.view_profile, name='view_profile'),
    # url(r'^store/$', CV.store, name='store'),
    # url(r'^central_jx/([a-zA-Z0-9_]+)/$', CV.central_jx, name='central_jx'),
    # 
    url(r'^master/', CV.master, name='master'),
    #url(r'^master_jx/([a-zA-Z0-9_]+)/$', CV.master_jx, name='master_jx'),
]


urlpatterns = [
    url(r'^$', CV.landing_page, name='landing_page'),

    url(r'^members/', include(members_url)),   # do not use a namespace, breaks allauth reverse urls 
    url(r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),	# necessary for postman
    
    url(r'^reference/', include(kingdoms_url, namespace='kingdoms')),
    url(r'^campaign/', include(campaign_url, namespace='campaign')),
    url(r'^central/', include(central_url, namespace='central')),
    
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', BV.not_found, name='not_found'),
]

kingdoms/views.py
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
KINGDOMS/VIEWS.py
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

import json
import random

from django.shortcuts import render
from django.http import JsonResponse
from django.utils.safestring import mark_safe
from django.contrib.auth.decorators import user_passes_test

import common.utility as CU
import kingdoms.kingdoms as KK


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
REFERENCE 
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""


def kingdoms(request):
    kingdoms = KK.Reporter.GetKingdoms()
    #kingdoms = ['Amniss', 'Dee\'Ench', 'Azzroth', 'Fahanzel', 'Labuluu', 'Qsi Tesan']
    cKingdom = random.choice(kingdoms)
    props = KK.Reporter.GetKingdomProperties(cKingdom)
    deck = KK.Reporter.GetKingdomDeck(cKingdom)
    
    context = {
        'kingdoms': mark_safe(json.dumps(kingdoms)),
        'cKingdom': cKingdom,
        'props': mark_safe(json.dumps(props)),
        'deck': mark_safe(json.dumps(deck)),
    }
    return render(request, 'kingdoms.html', context)


def special_cards(request):
    context = {
        'topRanks': mark_safe(json.dumps({})),
    }
    return render(request, 'special_cards.html', context)


def game_rules(request):
    context = {
        'topRanks': mark_safe(json.dumps({})),
    }
    return render(request, 'game_rules.html', context)


def reference_jx(request, command):
    
    CU.prog_lg.info("ajax command: " + command)
    
    
    if command == 'refresh_kingdom':
        kingdom = request.GET.get('kingdom')        
        props = KK.Reporter.GetKingdomProperties(kingdom)
        deck = KK.Reporter.GetKingdomDeck(kingdom)
        
        results = {
            'props': props,
            'deck': deck,
        }
        return JsonResponse(results, safe=False)
    
    
    else:
        msg = "command invalid: " + command
        CU.excp_lg.error(msg)
        return JsonResponse(msg, safe=False, status=404)  


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
DATA MANAGER 
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""


def data_load(request):
    kingdomCards = KK.Importer.GetKingdomCards()
    cardReport = KK.Reporter.GetCardReport()

    context = {
        'kingdomCards': mark_safe(json.dumps(kingdomCards)),
        'cardReport': mark_safe(json.dumps(cardReport)),
    }
    return render(request, 'data_load.html', context)


def manager_jx(request, command):
    
    CU.prog_lg.info("ajax command: " + command)
    
    
    if command == 'import_kingdoms':
        KK.Importer.ImportKingdoms()
        results = KK.Importer.GetKingdomCards()
        return JsonResponse(results, safe=False)
    
    elif command == 'import_cards':
        KK.Importer.ImportCards()
        results = KK.Importer.GetKingdomCards()
        return JsonResponse(results, safe=False)
    
    elif command == 'clear_tables':
        KK.Importer.ClearTables()
        results = KK.Importer.GetKingdomCards()
        return JsonResponse(results, safe=False)
    
    
    else:
        msg = "command invalid: " + command
        CU.excp_lg.error(msg)
        return JsonResponse(msg, safe=False, status=404)  




"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
END OF FILE
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

kingdoms/templates/data_load.html
{% extends "base_nav.html" %}
{% load utility_ttags %}
{% load staticfiles %}

{% comment %}
{% endcomment %}

{% block content %}


<div id="title_section" class="row">
    <div class="col-xs-12 format_center">
        <div class="inner_margin1 frame_header">
            <span class="font_title">Kingdom Data</span>
        </div>
    </div>
</div>


<div id="loadTables_section" class="row">
    
    <div class="col-xs-12">
        <div class="display_table">
            <div class="display_row">
                <div class="display_cellM">
                    <div class="inner_margin1 frame_header" style="margin-right: 0px;">
                        <span class="font_section">Load Data</span>
                    </div>
                </div>
                <div class="display_cellT" style="width: 100%;">
                    <div class="display_block frame_header format_separator">
                    </div>
                </div>
            </div>
        </div>
        <div style="display: none;">{% ctrl_status "kingdoms" %}</div>
    </div>
    
    <div class="col-xs-12 col-sm-6 col-xxl-4">
        <div class="display_block inner_margin1 outer_padding2 frame_entry">
            {% ctrl_label "load" "Load Tables" "font_strong" %}
            <div class="display_table">
                <div class="display_row">
                    <div class="display_cellT format_center" style="min-width: 200px;">
                        <br>
                        {% ctrl_button "kingdoms" "Load Kingdoms" %}
                        <br><br>
                        {% ctrl_button "cards" "Load Cards" %}
                        <br><br>
                        {% ctrl_button "reset" "Clear Tables" %} 
                    </div>
                    <div class="display_cellT">
                        {% ctrl_table "kingdomCards" %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="col-xs-12">
        <div class="display_block inner_margin1 outer_padding2 frame_entry">
            {% ctrl_label "report" "Card Report" "font_strong" %}
            
            {% ctrl_table "cardReport"  %}

        </div>
    </div>

</div>


<!-- SCRIPTS -->

<script>

$(document).ready(function()
{      
    $('body').css('cursor', 'wait');
    
    
    var jTable = $.parseJSON('{{ kingdomCards | escapejs }}');      //cl(jTable);
    DisplayKingdoms(jTable);
    
    $('#kingdoms_button').click(function() {
        ImportKingdoms();
    });
    
    $('#cards_button').click(function() {
        ImportCards();
    });
    
    $('#reset_button').click(function() {
        ClearTables();
    });
    

    var jTable = $.parseJSON('{{ cardReport | escapejs }}');      cl(jTable);

    if (jTable.length != 0)
    {
        SetDeluxeReport(jTable);
    }
    else
    {
        $('#cardReport_table').html("<div style='margin: 4px;'>No report available.</div>");
    }


    $('body').css('cursor', 'default');
});


function DisplayKingdoms(p_kingdoms)
{
    if (p_kingdoms.data.length != 0)
    {
        var fullT = JSONtoFullTable(p_kingdoms.data);
        SetDataTable('#kingdomCards_table', fullT, p_kingdoms.colFmt);
    }
    else
    {
        $('#kingdomCards_table').html("<div style='margin: 4px;'>No kingdoms available.</div>");
    }
}


function DisableForm()
{
    $('#kingdoms_status').parent().parent().hide(); 
    $('#kingdoms_button').prop('disabled', true);
    $('#cards_button').prop('disabled', true);
    $('#reset_button').prop('disabled', true);
    $('body').css('cursor', 'wait');
}


function EnableForm()
{
    $('#kingdoms_button').prop('disabled', false);
    $('#cards_button').prop('disabled', false);
    $('#reset_button').prop('disabled', false);
    $('body').css('cursor', 'default');    
}


// LOAD FUNCTIONS

function ImportKingdoms()
{
    DisableForm();
    
    $.ajax({
        type: 'POST',
        url: '{% url "kingdoms:manager_jx" "import_kingdoms" %}',
        success: function(p_data) {     //cl(p_data);
            DisplayKingdoms(p_data);
        }, 
        error: function(p_err) {
            ErrorToStatus(p_err.responseText, "ImportKingdoms()", '#kingdoms_status');
        },
        complete: function() {
            EnableForm();
        }
    });
}


function ImportCards()
{
    DisableForm();
    
    $.ajax({
        type: 'POST',
        url: '{% url "kingdoms:manager_jx" "import_cards" %}',
        success: function(p_data) {     //cl(p_data);
            DisplayKingdoms(p_data);
        }, 
        error: function(p_err) {
            ErrorToStatus(p_err.responseText, "ImportRaces()", '#kingdoms_status');
        },
        complete: function() {
            EnableForm();
        }
    });
}


function ClearTables()
{
    DisableForm();
    
    $.ajax({
        type: 'POST',
        url: '{% url "kingdoms:manager_jx" "clear_tables" %}',
        success: function(p_data) {     //cl(p_data);
            DisplayKingdoms(p_data);
        }, 
        error: function(p_err) {
            ErrorToStatus(p_err.responseText, "ClearTables()", '#kingdoms_status');
        },
        complete: function() {
            EnableForm();
        }
    });
}


// ANALYSIS FUNCTIONS


function SetDeluxeReport(p_report)
{   
    var tableId = '#cardReport_table';
    
    var table = $(tableId).DataTable( {
        data: p_report,
        aoColumns: [
            {
                mData: 'kingdom',
                title: 'Kingdom',
                sClass: 'format_fixline'
            },
            {
                mData: 'name',
                title: 'Name',
                sClass: 'format_fixline'
            }, 
            {
                mData: 'type',
                title: 'Type',
                sClass: 'format_center'
            }, 
            {
                mData: 'step1',
                title: 'Step 1'
            },
            {
                mData: 'step2',
                title: 'Step 2'
            },
            {
                mData: 'step3',
                title: 'Step 3'
            },
            {
                mData: 'step4',
                title: 'Step 4'
            },
        ], 
        bSort: true,
        scrollCollapse: true,
        paging: true,
        pageLength: 20,
        bFilter: true,
        bInfo: true,
        bDestroy: true 
    } );
}


</script>

{% endblock content %}

kingdoms/templates/game_rules.html
{% extends "base_nav.html" %}
{% load utility_ttags %}
{% load staticfiles %}

{% block content %}


<div id="title_section" class="row">
    <div class="col-xs-12 format_center">
        <div class="inner_margin1 frame_header">
            <span class="font_title">Game Rules</span>
        </div>
    </div>
</div>


<div id="_section" class="row">
    
    <div class="col-xs-12">
        <div class="display_table">
            <div class="display_row">
                <div class="display_cellM">
                    <div class="inner_margin1 frame_header" style="margin-right: 0px;">
                        <span class="font_section">Rule Books</span>
                    </div>
                </div>
                <div class="display_cellT" style="width: 100%;">
                    <div class="display_block frame_header format_separator">
                    </div>
                </div>
            </div>
        </div>
        <div style="display: none;">{% ctrl_status "section" %}</div>
    </div>
    
    <div class="col-xs-12 col-sm-6">
        <div class="display_block inner_margin1 outer_padding2 frame_entry" style="min-height: 100px;">
            <div class="inner_margin2">
                <a class="font_link" target="blank_" href="/static/documents/rulebook_pt.pdf">Livro de Regras</a>
            </div>
        </div>
    </div>
    
</div>


<script>


$(document).ready(function()
{      
    $('body').css('cursor', 'wait');
    

    //
    $('body').css('cursor', 'default');
});


</script>

{% endblock content %}

kingdoms/templates/kingdoms.html
{% extends "base_nav.html" %}
{% load utility_ttags %}
{% load staticfiles %}

{% block extra_head %}

<link rel="stylesheet" href="{% static 'PhotoSwipe-master/dist/photoswipe.css' %}"> 
<link rel="stylesheet" href="{% static 'PhotoSwipe-master/dist/default-skin/default-skin.css' %}"> 
<script src="{% static 'PhotoSwipe-master/dist/photoswipe.min.js' %}"></script> 
<script src="{% static 'PhotoSwipe-master/dist/photoswipe-ui-default.min.js' %}"></script> 

{% endblock %}


{% block content %}


<div id="title_section" class="row">
    <div class="col-xs-12 format_center">
        <div class="inner_margin1 frame_header">
            <span class="font_title">Kingdoms</span>
        </div>
    </div>
</div>


<div id="properties_section" class="row">
    
    <div class="col-xs-12">
        <div class="display_table">
            <div class="display_row">
                <div class="display_cellM">
                    <div class="inner_margin1 frame_header" style="margin-right: 0px;">
                        <span class="font_section">Properties</span>
                    </div>
                </div>
                <div class="display_cellT" style="width: 100%;">
                    <div class="display_block frame_header format_separator">
                    </div>
                </div>
            </div>
        </div>
        <div style="display: none;">{% ctrl_status "section" %}</div>
    </div>
    
    <div class="col-xs-12 col-sm-8 col-md-6 col-xxl-4">
        <div class="display_block inner_margin1 outer_padding2 frame_entry">
            {% ctrl_label "chs" "Choose Kingdom" "font_strong" %}
            {% ctrl_select "kingdom" "Kingdom" %}
            {% ctrl_table "kgProps" %}
        </div>
    </div>
    
    <div class="col-xs-12 col-sm-12 col-md-6 col-xxl-8">
        <div class="display_block inner_margin1 outer_padding2 frame_entry">
            {% ctrl_listing "attack" "Attack Cards" %}            
            {% ctrl_table "attack" %}
            <br>
            {% ctrl_listing "defense" "Defense Cards" %}            
            {% ctrl_table "defense" %}
            <br>
            {% ctrl_listing "spell" "Spell Cards" %}            
            {% ctrl_table "spell" %}
        </div>
    </div>
    
</div>


<div id="cards_section" class="row">
    
    <div class="col-xs-12">
        <div class="display_table">
            <div class="display_row">
                <div class="display_cellM">
                    <div class="inner_margin1 frame_header" style="margin-right: 0px;">
                        <span class="font_section">Cards</span>
                    </div>
                </div>
                <div class="display_cellT" style="width: 100%;">
                    <div class="display_block frame_header format_separator">
                    </div>
                </div>
            </div>
        </div>
        <div style="display: none;">{% ctrl_status "cards" %}</div>
    </div>
    
    <div class="col-xs-12">
        <div class="display_block inner_margin1 outer_padding2 frame_entry">
            <div id="attack_panel"></div>
        </div>
    </div>
    
    <div class="col-xs-12">
        <div class="display_block inner_margin1 outer_padding2 frame_entry">
            <div id="defense_panel"></div>
        </div>
    </div>
    
    <div class="col-xs-12">
        <div class="display_block inner_margin1 outer_padding2 frame_entry">
            <div id="spell_panel"></div>
        </div>
    </div>
    
</div>


<!-- Root element of PhotoSwipe. Must have class pswp. -->
<div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">

    <!-- Background of PhotoSwipe. 
         It's a separate element as animating opacity is faster than rgba(). -->
    <div class="pswp__bg"></div>

    <!-- Slides wrapper with overflow:hidden. -->
    <div class="pswp__scroll-wrap">

        <!-- Container that holds slides. 
            PhotoSwipe keeps only 3 of them in the DOM to save memory.
            Don't modify these 3 pswp__item elements, data is added later on. -->
        <div class="pswp__container">
            <div class="pswp__item"></div>
            <div class="pswp__item"></div>
            <div class="pswp__item"></div>
        </div>

        <!-- Default (PhotoSwipeUI_Default) interface on top of sliding area. Can be changed. -->
        <div class="pswp__ui pswp__ui--hidden">

            <div class="pswp__top-bar">

                <!--  Controls are self-explanatory. Order can be changed. -->

                <div class="pswp__counter"></div>

                <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
                <button class="pswp__button pswp__button--share" title="Share"></button>
                <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>
                <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>

                <!-- Preloader demo http://codepen.io/dimsemenov/pen/yyBWoR -->
                <!-- element will get class pswp__preloader--active when preloader is running -->
                <div class="pswp__preloader">
                    <div class="pswp__preloader__icn">
                      <div class="pswp__preloader__cut">
                        <div class="pswp__preloader__donut"></div>
                      </div>
                    </div>
                </div>
            </div>

            <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
                <div class="pswp__share-tooltip"></div> 
            </div>

            <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)">
            </button>

            <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)">
            </button>

            <div class="pswp__caption">
                <div class="pswp__caption__center"></div>
            </div>

        </div>

    </div>

</div>



<!-- SCRIPTS -->

<script>


$(document).ready(function()
{      
    $('body').css('cursor', 'wait');
    
    
    var kingdoms = $.parseJSON('{{ kingdoms | escapejs }}');
    
    $.each(kingdoms, function(key, val) {
        $('#kingdom_select').append($('<option>', {value : val }).text(val));
    });
    
    $('#kingdom_select').val("{{ cKingdom }}");
    
    $('#kingdom_select').change(function() {
        RefreshKingdom();
    });
    
    //
    var props = $.parseJSON('{{ props | escapejs }}');
    
    var fullT = JObjToFullTable(props)
    var trans = TransposeFullTable(fullT);
    SetVerticalTable('#kgProps_table', trans);
    
    //
    var deck = $.parseJSON('{{ deck | escapejs }}');     //cl(deck);
    DisplayDeck(deck);    
    DisplayCards(deck);
    
    $('body').css('cursor', 'default');
});


function DisplayDeck(p_deck)
{
    $('#attack_listing').text(p_deck.attack_cnt);
    $('#defense_listing').text(p_deck.defense_cnt);
    $('#spell_listing').text(p_deck.spell_cnt);
    
    var fullT = JSONtoFullTable(p_deck.attack);
    SetDataTable('#attack_table', fullT, p_deck.colFmt);
    
    var fullT = JSONtoFullTable(p_deck.defense);
    SetDataTable('#defense_table', fullT, p_deck.colFmt);
    
    var fullT = JSONtoFullTable(p_deck.spell);
    SetDataTable('#spell_table', fullT, p_deck.colFmt);
}

//
// DISPLAY GALLERIES

var PSWP_ELEM = {};
var ATTACK_ITEMS = [];
var DEFENSE_ITEMS = [];
var SPELL_ITEMS = [];

function DisplayCards(p_deck)
{
    var kingdom = $("#kingdom_select option:selected").text();
    kingdom = kingdom.toLowerCase().replaceAll(" ", "").replaceAll(/’/g, "");
    
    PSWP_ELEM = document.querySelectorAll('.pswp')[0];
    
    ATTACK_ITEMS = [];
    $.each(p_deck.attack, function(idx, val) {
        
        var cardName = val.name.toLowerCase().replaceAll(" ", "").replaceAll(/’/g, "");
        var fileName = "{0}_a_{1}.png".format(kingdom, cardName);
        var filePath = "/static/cards/" + fileName;
        
        // setup the thumbnail panel
        
        var html = '<img id="attack_{0}_thumb" class="card_kingdom" src="{1}" />'.format(idx, filePath);
        $('#attack_panel').append(html);
        $('#attack_{0}_thumb'.format(idx)).click(OpenAttackGallery);
        
        // setup images for viewing
        
        var newItem = {'src': filePath, 'w': 676, 'h': 1054 };
        ATTACK_ITEMS.push(newItem);
    });
    
    DEFENSE_ITEMS = [];
    $.each(p_deck.defense, function(idx, val) {
        
        var cardName = val.name.toLowerCase().replaceAll(" ", "").replaceAll(/’/g, "");
        var fileName = "{0}_d_{1}.png".format(kingdom, cardName);
        var filePath = "/static/cards/" + fileName;
        
        // setup the thumbnail panel
        
        var html = '<img id="defense_{0}_thumb" class="card_kingdom" src="{1}" />'.format(idx, filePath);
        $('#defense_panel').append(html);
        $('#defense_{0}_thumb'.format(idx)).click(OpenDefenseGallery);
        
        // setup images for viewing
        
        var newItem = {'src': filePath, 'w': 676, 'h': 1054 };
        DEFENSE_ITEMS.push(newItem);
    });
    
    SPELL_ITEMS = [];
    $.each(p_deck.spell, function(idx, val) {
        
        var cardName = val.name.toLowerCase().replaceAll(" ", "").replaceAll(/’/g, "");
        var fileName = "{0}_s_{1}.png".format(kingdom, cardName);
        var filePath = "/static/cards/" + fileName;
        
        // setup the thumbnail panel
        
        var html = '<img id="spell_{0}_thumb" class="card_kingdom" src="{1}" />'.format(idx, filePath);
        $('#spell_panel').append(html);
        $('#spell_{0}_thumb'.format(idx)).click(OpenSpellGallery);
        
        // setup images for viewing
        
        var newItem = {'src': filePath, 'w': 676, 'h': 1054 };
        SPELL_ITEMS.push(newItem);
    });
    
}


function OpenAttackGallery()
{
    var htmlID = $(this).attr('id');        // get the html-id of the calling element
    var id = htmlID.match(/\d+/)[0];        // get the first number in string
    
    var options = {
        index: parseInt(id),        
        bgOpacity: 0.5,
        shareEl: false,
        history: false,
        timeToIdle: 10000,
    };
    
    var gallery = new PhotoSwipe( PSWP_ELEM, PhotoSwipeUI_Default, ATTACK_ITEMS, options );
    gallery.init();
}


function OpenDefenseGallery()
{
    var htmlID = $(this).attr('id');        // get the html-id of the calling element
    var id = htmlID.match(/\d+/)[0];        // get the first number in string
    
    var options = {
        index: parseInt(id),        
        bgOpacity: 0.5,
        shareEl: false,
        history: false,
        timeToIdle: 10000,
    };
    
    var gallery = new PhotoSwipe( PSWP_ELEM, PhotoSwipeUI_Default, DEFENSE_ITEMS, options );
    gallery.init();
}


function OpenSpellGallery()
{
    var id = $(this).attr('id').match(/\d+/)[0];   
    
    var options = {
        index: parseInt(id),        
        bgOpacity: 0.5,
        shareEl: false,
        history: false,
        timeToIdle: 10000,
    };
    
    var gallery = new PhotoSwipe( PSWP_ELEM, PhotoSwipeUI_Default, SPELL_ITEMS, options );
    gallery.init();
}

//
// ajax requests

function RefreshKingdom()
{    
    $('body').css('cursor', 'wait');
    
    var kingdom = $("#kingdom_select option:selected").text();
    
    $('#attack_table').html(null);
    $('#defense_table').html(null);
    $('#spell_table').html(null);
    
    $('#attack_panel').html(null);
    $('#defense_panel').html(null);
    $('#spell_panel').html(null);
    
    $.ajax({
        type: 'GET',
        url: '{% url "kingdoms:reference_jx" "refresh_kingdom" %}',
        data: {'kingdom': kingdom,},
        success: function(p_data) {         //cl(p_data);
            var fullT = JObjToFullTable(p_data.props)
            var trans = TransposeFullTable(fullT);
            SetVerticalTable('#kgProps_table', trans);
            
            DisplayDeck(p_data.deck);
            DisplayCards(p_data.deck);
        }, 
        error: function(p_err) {
            ErrorToStatus(p_err.responseText, "RefreshKingdom()", '#error_status');
        },
        complete: function() {
            $('body').css('cursor', 'default');
        }
    });
}



</script>

{% endblock content %}